# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
  - 3.5
  - 3.4
  - 2.7
  - pypy

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -e .

# command to run tests, e.g. python setup.py test
script: python -m unittest discover

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: timmmartin19
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: timmmartin19/boto3_retry
    condition: $TOXENV == py27
