after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  distributions: sdist bdist_wheel
  on:
    repo: timmartin19/boto3-retry
    tags: true
  password:
    secure: XQgJ4hD4nJ5nxdSK0snJLld/TADNhOFDBhegeFKC/WaRS/rPKE/SIb4JVdF8HHh4KgDUXIx66wssMwD836/IenwJw27xKUq5W7khT9EO+5TE9S8gFU/grZ5Md71+fEbCOkPYnaq2B04QJM3YYr+DtgLjHvC9/qq8Ba77mv5tgwifnCxsUvKKoQAlJrP2zf7ADgGN9T71ySS8BBjeeX01ngHwVTQ+Tj7YxFxM7tEv45ySSt1AYsTBvh/+Ih/NCJDXQ6W9ER2tZFCd3q2oyLaAt2TER60gXsNBQLp8ukdUNqKiozemz0K5u3MyrlzR9Z6UCPYPDDbParS/5zTuEJLVvtfAqse8ML7WdD2tV7W18L+63ojFmDWaVpBZHdxgFYvyyTcpEhWQxvAeE3qRTXHsIO7L1f/AwoNsjdTuD5Xp6f/lPrBquExT8XK8trPKJ0p91lFbAgjJR+c8t3CtuB9fMhYyylwl+z4RY5Mb22QWzxZn0/2TqgcyQ8HrdQzwwK9cFQ3PTAc5vxnL52VR0+Q7jCtLtctJalr8sRGuiT2ecKtnsp42hLeEHSV/Q2dn/TyCmsRZMC5T2J/oyY+Vm8BMIJBvgxqBOKF3IYN/TsDMEt96u6oNKdj33k/nLVNUsjk/PQQwAX+93lhEtxcx4Kxp39bEofQRElFSMGloxSzrVdc=
  provider: pypi
  user: timmmartin19
install: pip install -e .
language: python
python:
- 3.5
- 3.4
- pypy
script: python -m unittest discover
