after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  distributions: sdist bdist_wheel
  on:
    repo: timmartin19/boto3-retry
    tags: true
  password:
    secure: C730fc2lV6m0HcQiYP+EXb6UaNx4aLG5fjASL3bWIZH0auMOAXzSc7v9A+NDzW8lyBR5zSKchRZIH0iBKbKYt7ZijZAEawtxPqXkhJRfuAxkMILJY9R2RNtjYg7zLrcuizF4/OeK8uUvO5Z5rpvEhJtNkAz+juT1cRuYi0DFgM2ZDLZUqrQBTCfe4UWl/I7fL2GssrGb0FT5+Veta2Mni3+A+lcNSj1vI9Bn3IxuxRRVaMGZ+jCBOwB/2/7H3NmN5gP0ZWd/banPgvEI56NaBcg6DquGRwoKhjbt16R3o6DZiz2zF3BE/ZNnKCvUqesOib79Ds0S/A3f6XMHtgFSwpdl/fyd1jbd8+UZlGtVnSJJopjc4KnBDpbGO4ZFlDUIel+kmODZR8fl6w7sZihYikrDMM4h9d92FPOvEpWhjs0UzkpELmkUvor8eUQGhJrDX03xY8OdHNhnWxgr0MygTOu/ADQZgqS1tTEqpJmksHVHH3cP6dDo7LhrUbu9OJN29yGoroBvdSzlRZ15/rPlLwEWIJg+ocEgVLFGReY16VgbaQFXhZSqVX0w56MNK8vM/e3ky4uuT0kSYZJOPJxYYC0bX7x8OKWbRiHeuIKtoTp+53lOij402y+em5zPvdko80YBkmt4ikR1OsjY6+vsbmiHIxo5oqG1g6EXR8tHpfo=
  provider: pypi
  user: timmartin19
install: pip install -e .
language: python
python:
- 3.5
- 3.4
- pypy
script: python -m unittest discover
